Icon lib
feltcoop/felt pull request #10
Opened 2021-04-01 15:17 UTC by greatbacon

# Pull Request 💚-🐑👁️
#9 
In order to help us easily visualize & review components, please consider putting a [Svelte REPL](https://svelte.dev/repl) example below: raw typescript means no REPL (I think)

2021-04-01 15:36 UTC, ryanatkn commented on src/routes/index.svelte
> +	import * as icons from '$lib/icons.ts';
I'd prefer to change this to explicit imports, unless we're using `icons` as a collection, e.g. to display all of them in a list, or perform lookups from a name. It's less convenience, especially the more you use, but by going with `import {mushroomIcon} from '$lib/icons.ts` instead of the `* as` syntax, our build tools can know to bundle only the included identifiers. In practice, if everyone in the Felt ecosystem imports just the icons they use, and then runs it through the Gro/SvelteKit tools, they'll have the minimal set of icons that they use. Otherwise, every Felt app deployed that uses any icons will have the entire module.

2021-04-01 15:41 UTC, ryanatkn commented
Idea: would you like to include a new component, maybe `Icons.svelte`, used in `routes/index.svelte` like this:

```svelte
<script>
  // routes/index.svelte
  import Icons from '$lib/Icons.svelte';
  import * as icons from '$lib/icons.js';
</script>

<Icons {icons} />
```

And then implement `src/lib/Icons.svelte` so it renders everything, the icon + label.

2021-04-01 21:26 UTC, ryanatkn requested changes
Can't wait to use this as an end user! The imports are the only change request. Also we should open an issue to discuss related components unless you want to add to this PR.

2021-04-01 23:10 UTC, greatbacon commented on src/routes/index.svelte
> +	import * as icons from '$lib/icons.ts';
Yeah, I was being lazy when I set up the test page cause I wasn't really sure what i'd be using in the first place. I'll clean it up.

2021-04-01 23:12 UTC, greatbacon commented
> Idea: would you like to include a new component, maybe `Icons.svelte`, used in `routes/index.svelte` like this:
> 
> ```svelte
> <script>
>   // add this stuff to `src/routes/index.svelte`
>   import Icons from '$lib/Icons.svelte';
>   import * as icons from '$lib/icons.js';
> </script>
> 
> <Icons {icons} />
> ```
> 
> And then implement `src/lib/Icons.svelte` so it renders everything, the icon + label.

Yeah, I think a page that shows every Icon + shortcut could be a useful component!

2021-04-02 03:35 UTC, ryanatkn approved these changes
Nice ⚡

2021-04-06 03:11 UTC, merged